name: dl-bsde
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - tqdm>=4.62.0
  - scikit-learn>=1.0.0
  - plotly>=5.0.0
  - seaborn>=0.11.0
  - pyyaml>=6.0.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pip
  - pip:
    - tensorboard>=2.8.0
    - wandb>=0.12.0
