# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: polymarket
  labels:
    app: postgres
    component: database
type: Opaque
data:
  # Base64 encoded passwords (replace with actual secure values)
  POSTGRES_PASSWORD: Y2hhbmdlbWVfaW5fcHJvZHVjdGlvbg==  # changeme_in_production
  DATA_COLLECTOR_DB_PASSWORD: ZGF0YV9jb2xsZWN0b3JfcGFzc3dvcmRfY2hhbmdlX21l  # data_collector_password_change_me
  RISK_MANAGER_DB_PASSWORD: cmlza19tYW5hZ2VyX3Bhc3N3b3JkX2NoYW5nZV9tZQ==  # risk_manager_password_change_me
  TRADING_ENGINE_DB_PASSWORD: dHJhZGluZ19lbmdpbmVfcGFzc3dvcmRfY2hhbmdlX21l  # trading_engine_password_change_me
---
# Redis Secret
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: polymarket
  labels:
    app: redis
    component: cache
type: Opaque
data:
  REDIS_PASSWORD: Y2hhbmdlbWVfaW5fcHJvZHVjdGlvbg==  # changeme_in_production
---
# Polymarket API Secret
apiVersion: v1
kind: Secret
metadata:
  name: polymarket-api-secret
  namespace: polymarket
  labels:
    app: polymarket-trading
    component: api
type: Opaque
data:
  POLYMARKET_API_KEY: eW91cl9wb2x5bWFya2V0X2FwaV9rZXlfaGVyZQ==  # your_polymarket_api_key_here
  POLYMARKET_PRIVATE_KEY: eW91cl9wb2x5bWFya2V0X3ByaXZhdGVfa2V5X2hlcmU=  # your_polymarket_private_key_here
---
# JWT and Security Secret
apiVersion: v1
kind: Secret
metadata:
  name: security-secret
  namespace: polymarket
  labels:
    app: polymarket-trading
    component: security
type: Opaque
data:
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl  # your_jwt_secret_key_here
---
# Proxy Configuration Secret
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret
  namespace: polymarket
  labels:
    app: polymarket-trading
    component: proxy
type: Opaque
data:
  PROXY_USERNAME: ""  # Empty for development
  PROXY_PASSWORD: ""  # Empty for development