[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "picker-python-project"
version = "0.1.0"
dependencies = [
    "requests>=2.25.1"
]
requires-python = ">=3.7"

[tool.setuptools]
packages = {find = {}}
