npmRegistryServer: "https://registry.npmmirror.com"
# Enable node-modules linker if you prefer classic node_modules layout (optional)
# nodeLinker: "node-modules"

# Enable Yarn cache in project (optional)
enableGlobalCache: true
# Disable strict SSL if your environment has TLS interception (not recommended)
# unsafeHttpWhitelist:
#  - "registry.npmmirror.com"

# If you use GitHub packages or other registries, define them here:
# "npmScopes":
#   "your-scope":
#     npmRegistryServer: "https://registry.npmjs.org"
