[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.7.6"
optimizer = true
optimizer_runs = 200

# Remappings for Uniswap V3
remappings = [
    "v3-core/=lib/v3-core/",
    "v3-periphery/=lib/v3-periphery/",
]

# RPC endpoints
[rpc_endpoints]
bnb_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"
bnb_mainnet = "https://bsc-dataseed.binance.org/"

# BscScan API for contract verification
# Using BscScan's V2 API endpoints
[etherscan]
bnb_testnet = { key = "${BSCSCAN_API_KEY}" }
bnb_mainnet = { key = "${BSCSCAN_API_KEY}" }
