[profile.default]
src = "contracts"
out = "artifacts-foundry"
cache_path = 'cache-foundry'
libs = ["lib"]
cache = true
evm_version = 'cancun'
solc = "0.8.26"
optimizer = true
optimizer_runs = 200

# 测试网 RPC 配置
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

# Etherscan API keys for verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }